[project]
name = "brave"
version = "0.1.0"
description = "Force rich loco-manipulation model for humanoid robots"
readme = "README.md"
requires-python = ">=3.13.13"
dependencies = ["mjlab==1.5.3"]

# TODO: add ruff linting

[project.entry-points."mjlab.tasks"]
brave = "brave"

[project.optional-dependencies]
notebooks = ["jupyter==1.1.1", "matplotlib==3.11.1"]

[build-system]
requires = ["uv_build==0.12"]
build-backend = "uv_build"
